name: Installer ISO build
on:
  workflow_dispatch:
  push:
    branches:
    - 'master'
jobs:
  build:
    name: Installer ISO build
    runs-on: ubuntu-latest
    outputs:
      iso_file_name: ${{ steps.build_iso.outputs.iso_file_name }}
      version: ${{ steps.build_iso.outputs.version }}
      id: ${{ steps.build_iso.outputs.id }}
    steps:
      - uses: actions/checkout@v3
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: Build ISO
        id: build_iso
        run: ./build-iso-docker.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: chimeraos-2023.02.20-x86_64.iso
          path: /root/chimeraos/output/chimeraos-2023.02.20-x86_64.iso
